@tool
extends Node



# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	var mesh := ArrayMesh.new()
	var aabb := AABB(Vector3(),Vector3(1,1,1))
	var tool := SurfaceTool.new()
	tool.begin(Mesh.PRIMITIVE_TRIANGLES)
	
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(0))
	tool.set_uv(Vector2(1,0))
	tool.add_vertex(aabb.get_endpoint(4))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(5))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(5))
	tool.set_uv(Vector2(0,1))
	tool.add_vertex(aabb.get_endpoint(1))
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(0))
	tool.commit(mesh)
	
	tool.begin(Mesh.PRIMITIVE_TRIANGLES)
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(2))
	tool.set_uv(Vector2(1,0))
	tool.add_vertex(aabb.get_endpoint(6))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(4))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(4))
	tool.set_uv(Vector2(0,1))
	tool.add_vertex(aabb.get_endpoint(0))
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(2))
	tool.commit(mesh)
	
	tool.begin(Mesh.PRIMITIVE_TRIANGLES)
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(3))
	tool.set_uv(Vector2(1,0))
	tool.add_vertex(aabb.get_endpoint(2))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(0))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(0))
	tool.set_uv(Vector2(0,1))
	tool.add_vertex(aabb.get_endpoint(1))
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(3))
	tool.commit(mesh)
	
	tool.begin(Mesh.PRIMITIVE_TRIANGLES)
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(7))
	tool.set_uv(Vector2(1,0))
	tool.add_vertex(aabb.get_endpoint(3))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(1))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(1))
	tool.set_uv(Vector2(0,1))
	tool.add_vertex(aabb.get_endpoint(5))
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(7))
	tool.commit(mesh)
	
	tool.begin(Mesh.PRIMITIVE_TRIANGLES)
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(6))
	tool.set_uv(Vector2(1,0))
	tool.add_vertex(aabb.get_endpoint(7))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(5))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(5))
	tool.set_uv(Vector2(0,1))
	tool.add_vertex(aabb.get_endpoint(4))
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(6))
	tool.commit(mesh)
	
	tool.begin(Mesh.PRIMITIVE_TRIANGLES)
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(6))
	tool.set_uv(Vector2(1,0))
	tool.add_vertex(aabb.get_endpoint(2))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(3))
	tool.set_uv(Vector2(1,1))
	tool.add_vertex(aabb.get_endpoint(3))
	tool.set_uv(Vector2(0,1))
	tool.add_vertex(aabb.get_endpoint(7))
	tool.set_uv(Vector2(0,0))
	tool.add_vertex(aabb.get_endpoint(6))
	
	$MeshInstance3D.mesh = tool.commit(mesh)
